name: Trigger Build on PR

on:
  workflow_run:
    workflows: [Flake â„ï¸ Lock ğŸ”’ï¸ Updater âœ¨]
    types: [completed]

jobs:
  trigger-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
